export const DATABASE_PROVIDER = 'DATABASE_PROVIDER';
export const SUPABASE_ADMIN_PROVIDER = 'SUPABASE_ADMIN_PROVIDER';
export const SUPABASE_ANON_PROVIDER = 'SUPABASE_ANON_PROVIDER';
export const STORAGE_PROVIDER = 'STORAGE_PROVIDER';
